name: Build Executable for Windows

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pygit2 pgzip
        pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
        pip install -r requirements.txt

    - name: Run tests
      run: python launch.py --tests basic_features --no-half --disable-opt-split-attention --use-cpu all --skip-torch-cuda-test

    - name: Build Executable by pyinstaller
      run: .\build.bat

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
